import {questions} from './questions.js';
export const characters=[{emoji:'🦊',name:'Fox'},{emoji:'🐸',name:'Frog'},{emoji:'🐼',name:'Panda'},{emoji:'🐱',name:'Cat'},{emoji:'🐙',name:'Octopus'},{emoji:'🦉',name:'Owl'},{emoji:'🐻',name:'Bear'},{emoji:'🐰',name:'Rabbit'},{emoji:'🦁',name:'Lion'},{emoji:'🦔',name:'Hedgehog'}];
export function shuffle(items){const a=[...items];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
export function makeGame(name,seconds=30){return {name:name.trim().slice(0,50)||'Our quiz night',seconds:[20,30,45,60].includes(seconds)?seconds:30,phase:'lobby',index:0,deadline:0,players:[],deck:[],used:[],answers:{},revision:0};}
export function addPlayer(g,id,name,character){if(g.phase!=='lobby')throw Error('This game has started. Join after the rematch.');if(g.players.length>=8)throw Error('This table is full (8 players maximum).');name=String(name||'').trim().slice(0,24);if(!name)throw Error('Enter your name.');if(g.players.some(p=>p.name.toLowerCase()===name.toLowerCase()))throw Error('That name is taken. Try another.');if(!Number.isInteger(character)||!characters[character])throw Error('Choose a character.');g.players.push({id,name,character,score:0,connected:true});g.revision++;}
export function start(g,now=Date.now()){if(g.phase!=='lobby')throw Error('This quiz has already started.');if(g.players.filter(p=>p.connected).length<2)throw Error('Wait for one more player to join.');g.deck=[];for(const round of ['The warm-up','Screen & sound','The final call']){const pool=questions.filter(q=>q.round===round),fresh=pool.filter(q=>!g.used.includes(q.q));const picked=[...shuffle(fresh),...shuffle(pool.filter(q=>g.used.includes(q.q)))].slice(0,5);g.deck.push(...picked.map(q=>{const order=shuffle([0,1,2,3]);return {...q,o:order.map(i=>q.o[i]),a:order.indexOf(q.a)};}));}g.used=[...new Set([...g.used,...g.deck.map(q=>q.q)])];g.phase='question';g.index=0;g.answers={};g.players.forEach(p=>p.score=0);g.deadline=now+g.seconds*1000;g.revision++;}
export function answer(g,id,index,choice,now=Date.now()){if(g.phase!=='question'||index!==g.index||now>=g.deadline)throw Error('Answers are closed for this question.');if(!g.players.some(p=>p.id===id&&p.connected))throw Error('Player is not connected.');if(!Number.isInteger(choice)||choice<0||choice>3)throw Error('Choose an answer.');if(Object.hasOwn(g.answers,id))throw Error('Your answer is already locked in.');g.answers[id]=choice;g.revision++;if(g.players.filter(p=>p.connected).every(p=>Object.hasOwn(g.answers,p.id)))reveal(g);}
export function reveal(g){if(g.phase!=='question')return;g.phase='reveal';for(const p of g.players)if(g.answers[p.id]===g.deck[g.index].a)p.score+=100;g.revision++;}
export function next(g,now=Date.now()){if(g.phase!=='reveal')throw Error('Wait for the answers to be revealed.');if(g.index===g.deck.length-1){g.phase='finished';}else{g.index++;g.phase='question';g.answers={};g.deadline=now+g.seconds*1000;}g.revision++;}
export function rematch(g){if(g.phase!=='finished')throw Error('Finish this quiz first.');g.phase='lobby';g.answers={};g.players=g.players.filter(p=>p.connected);g.players.forEach(p=>p.score=0);g.index=0;g.revision++;}
export function snapshot(g,id,now=Date.now()){const q=g.deck[g.index],shown=['reveal','finished'].includes(g.phase);return {name:g.name,phase:g.phase,index:g.index,seconds:g.seconds,remaining:Math.max(0,g.deadline-now),revision:g.revision,players:g.players.map(p=>({...p,answered:Object.hasOwn(g.answers,p.id)})),mine:Object.hasOwn(g.answers,id)?g.answers[id]:null,question:q&&g.phase!=='lobby'?{q:q.q,o:q.o,round:q.round,category:q.category,...(shown?{a:q.a,f:q.f}:{})}:null};}
