export const questions = [
{round:'The warm-up',category:'General knowledge',q:'Which planet has the most prominent ring system?',o:['Mars','Saturn','Venus','Mercury'],a:1,f:'Saturn’s rings are made mostly of countless pieces of ice.'},
{round:'The warm-up',category:'Geography',q:'Which city is home to the Colosseum?',o:['Athens','Madrid','Rome','Lisbon'],a:2,f:'The Colosseum is an ancient Roman amphitheatre in Rome.'},
{round:'The warm-up',category:'Science',q:'What is the chemical symbol for gold?',o:['Ag','Go','Gd','Au'],a:3,f:'Au comes from aurum, the Latin word for gold.'},
{round:'The warm-up',category:'Food & drink',q:'Which of these is the main ingredient in traditional hummus?',o:['Chickpeas','Lentils','White beans','Peas'],a:0,f:'Hummus is traditionally made with chickpeas, tahini, lemon and garlic.'},
{round:'The warm-up',category:'Nature',q:'How many hearts does an octopus have?',o:['One','Two','Three','Four'],a:2,f:'Two hearts pump blood to the gills; the third pumps it to the body.'},
{round:'Screen & sound',category:'Movies',q:'In The Lion King, what is Simba’s father called?',o:['Scar','Mufasa','Rafiki','Zazu'],a:1,f:'Mufasa is the king of the Pride Lands and Simba’s father.'},
{round:'Screen & sound',category:'Music',q:'Which band released Bohemian Rhapsody?',o:['The Beatles','ABBA','Queen','Pink Floyd'],a:2,f:'Queen released Bohemian Rhapsody in 1975.'},
{round:'Screen & sound',category:'Television',q:'What is the name of the coffee shop in Friends?',o:['Central Perk','The Daily Grind','Monk’s Café','Coffee Central'],a:0,f:'Central Perk is the group’s regular meeting place.'},
{round:'Screen & sound',category:'Movies',q:'Which film features the character Jack Sparrow?',o:['Hook','Treasure Planet','Peter Pan','Pirates of the Caribbean'],a:3,f:'Captain Jack Sparrow first appeared in The Curse of the Black Pearl.'},
{round:'Screen & sound',category:'Music',q:'Which instrument usually has 88 keys?',o:['Violin','Piano','Trumpet','Flute'],a:1,f:'A standard modern piano has 52 white keys and 36 black keys.'},
{round:'The final call',category:'Geography',q:'Which is the largest ocean on Earth?',o:['Atlantic','Indian','Pacific','Arctic'],a:2,f:'The Pacific is the largest and deepest ocean.'},
{round:'The final call',category:'Sport',q:'How many players does a football team have on the pitch at the start of a match?',o:['Nine','Ten','Eleven','Twelve'],a:2,f:'Each team starts with eleven players, including the goalkeeper.'},
{round:'The final call',category:'Literature',q:'Who wrote Pride and Prejudice?',o:['Jane Austen','Charlotte Brontë','Mary Shelley','Virginia Woolf'],a:0,f:'Jane Austen’s Pride and Prejudice was published in 1813.'},
{round:'The final call',category:'Science',q:'Which gas do plants absorb during photosynthesis?',o:['Oxygen','Helium','Hydrogen','Carbon dioxide'],a:3,f:'Plants use carbon dioxide and water to make sugars with light energy.'},
{round:'The final call',category:'Around the world',q:'Which country is home to the ancient city of Petra?',o:['Egypt','Jordan','Greece','Türkiye'],a:1,f:'Petra is famous for its rock-cut architecture in southern Jordan.'}
];
questions.push(
{round:'The warm-up',category:'Geography',q:'What is the capital of Japan?',o:['Kyoto','Tokyo','Osaka','Seoul'],a:1,f:'Tokyo is the capital of Japan.'},
{round:'The warm-up',category:'Nature',q:'Which is the largest living land animal?',o:['Giraffe','White rhinoceros','African bush elephant','Hippopotamus'],a:2,f:'The African bush elephant is the largest living land animal.'},
{round:'The warm-up',category:'Science',q:'At sea level, at what temperature does pure water boil?',o:['50°C','75°C','100°C','150°C'],a:2,f:'Pure water boils at 100°C at standard atmospheric pressure.'},
{round:'The warm-up',category:'Food',q:'Which fruit is traditionally used to make guacamole?',o:['Avocado','Mango','Lime','Papaya'],a:0,f:'Avocado is the main ingredient in guacamole.'},
{round:'The warm-up',category:'Space',q:'Which planet is closest to the Sun?',o:['Venus','Earth','Mercury','Mars'],a:2,f:'Mercury is the innermost planet in our Solar System.'},
{round:'The warm-up',category:'Animals',q:'What do caterpillars develop into?',o:['Beetles and flies','Butterflies and moths','Bees and wasps','Spiders'],a:1,f:'A caterpillar is the larval stage of a butterfly or moth.'},
{round:'The warm-up',category:'Geography',q:'On which continent is the Sahara Desert?',o:['Asia','Australia','Africa','South America'],a:2,f:'The Sahara stretches across North Africa.'},
{round:'The warm-up',category:'Food',q:'What is tofu traditionally made from?',o:['Rice','Soybeans','Potatoes','Almonds'],a:1,f:'Tofu is made by coagulating soy milk and pressing the curds.'},
{round:'The warm-up',category:'Science',q:'What is the chemical formula for water?',o:['CO₂','H₂O','O₂','NaCl'],a:1,f:'Each water molecule contains two hydrogen atoms and one oxygen atom.'},
{round:'The warm-up',category:'Nature',q:'Which of these mammals lays eggs?',o:['Koala','Platypus','Dolphin','Kangaroo'],a:1,f:'The platypus is a monotreme, a type of egg-laying mammal.'},
{round:'Screen & sound',category:'Movies',q:'Who directed Jurassic Park (1993)?',o:['James Cameron','Steven Spielberg','George Lucas','Tim Burton'],a:1,f:'Steven Spielberg directed the 1993 film Jurassic Park.'},
{round:'Screen & sound',category:'Music',q:'Which band recorded Dancing Queen?',o:['Queen','ABBA','Bee Gees','Fleetwood Mac'],a:1,f:'ABBA released Dancing Queen in 1976.'},
{round:'Screen & sound',category:'Movies',q:'What is the name of the cowboy toy in Toy Story?',o:['Buzz','Woody','Rex','Andy'],a:1,f:'Woody is the pull-string cowboy toy voiced by Tom Hanks.'},
{round:'Screen & sound',category:'Music',q:'Which musician was nicknamed the King of Pop?',o:['Elvis Presley','Prince','Michael Jackson','David Bowie'],a:2,f:'Michael Jackson is widely known as the King of Pop.'},
{round:'Screen & sound',category:'Movies',q:'In Finding Nemo, what type of fish is Nemo?',o:['Goldfish','Clownfish','Angelfish','Pufferfish'],a:1,f:'Nemo and his father Marlin are clownfish.'},
{round:'Screen & sound',category:'Movies',q:'Which fictional school does Harry Potter attend?',o:['Nevermore','Hogwarts','Narnia Academy','Xavier’s School'],a:1,f:'Harry attends Hogwarts School of Witchcraft and Wizardry.'},
{round:'Screen & sound',category:'Music',q:'Which city are The Beatles originally from?',o:['London','Manchester','Liverpool','Birmingham'],a:2,f:'The Beatles formed in Liverpool, England.'},
{round:'Screen & sound',category:'Movies',q:'Which film features the song Let It Go?',o:['Moana','Tangled','Frozen','Encanto'],a:2,f:'Elsa sings Let It Go in Disney’s Frozen.'},
{round:'Screen & sound',category:'Television',q:'Which animated family lives in Springfield?',o:['The Simpsons','The Flintstones','The Jetsons','The Addams Family'],a:0,f:'The Simpsons live at 742 Evergreen Terrace in Springfield.'},
{round:'Screen & sound',category:'Music',q:'How many strings does a standard violin have?',o:['Three','Four','Five','Six'],a:1,f:'A standard violin has four strings, tuned G, D, A and E.'},
{round:'The final call',category:'Geography',q:'Which country is shaped like a boot?',o:['Portugal','Italy','Norway','Croatia'],a:1,f:'Italy’s peninsula is famously shaped like a boot.'},
{round:'The final call',category:'Sport',q:'In tennis, what is a score of zero called?',o:['Love','Nil','Blank','Duck'],a:0,f:'A score of zero in tennis is called love.'},
{round:'The final call',category:'Literature',q:'Who wrote Romeo and Juliet?',o:['Charles Dickens','William Shakespeare','Oscar Wilde','Mark Twain'],a:1,f:'Romeo and Juliet is a tragedy by William Shakespeare.'},
{round:'The final call',category:'Science',q:'What is the hardest natural mineral on the Mohs scale?',o:['Quartz','Ruby','Diamond','Topaz'],a:2,f:'Diamond has a hardness of 10 on the Mohs scale.'},
{round:'The final call',category:'Around the world',q:'Which country gave the Statue of Liberty to the United States?',o:['France','Italy','Spain','Germany'],a:0,f:'The Statue of Liberty was a gift from France.'},
{round:'The final call',category:'Geography',q:'What is the capital of Cyprus?',o:['Limassol','Larnaca','Nicosia','Paphos'],a:2,f:'Nicosia is the capital of Cyprus.'},
{round:'The final call',category:'Sport',q:'How many rings are on the Olympic symbol?',o:['Four','Five','Six','Seven'],a:1,f:'The Olympic symbol has five interlaced rings.'},
{round:'The final call',category:'Science',q:'Which organ pumps blood around the human body?',o:['Liver','Lung','Heart','Kidney'],a:2,f:'The heart pumps blood through the circulatory system.'},
{round:'The final call',category:'Art',q:'Who painted the Mona Lisa?',o:['Michelangelo','Leonardo da Vinci','Raphael','Vincent van Gogh'],a:1,f:'Leonardo da Vinci painted the Mona Lisa.'},
{round:'The final call',category:'Numbers',q:'What is the only even prime number?',o:['Zero','Two','Four','Six'],a:1,f:'Two is prime; all larger even numbers are divisible by two.'}
);
